package main

import (
	"agentotelstack/gateway/internal/query"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"
)

func TestProjectIsSafeForUntrustedTelemetry(t *testing.T) {
	secret := "Bearer live-secret-cookie password=do-not-leak"
	in := map[string]any{
		"message":       "hello\x1b[31m world",
		"authorization": secret, "cookie": secret, "api_key": secret,
		"password": secret, "http.url": "https://example.test/pay?token=" + secret + "#frag",
		"db.statement": "select password from users", "gen_ai.prompt": secret,
		"body": secret, "trace_id": "abc",
	}
	b, _ := json.Marshal(project(in))
	out := string(b)
	if strings.Contains(out, "live-secret") || strings.Contains(out, "password=do-not-leak") || strings.Contains(out, "gen_ai") {
		t.Fatalf("secret or forbidden field escaped projection: %s", out)
	}
	if strings.ContainsAny(out, "\x00\x1b") {
		t.Fatalf("control character escaped projection: %q", out)
	}
}

func TestValidateProjectRequiresUUIDv4(t *testing.T) {
	valid := "550e8400-e29b-41d4-a716-446655440000"
	if err := query.ValidateProject(valid); err != nil {
		t.Fatalf("valid UUIDv4 rejected: %v", err)
	}
	for _, value := range []string{
		"550e8400-e29b-11d4-a716-446655440000", // v1
		"550e8400-e29b-51d4-a716-446655440000", // v5
		"b4ae8608-e1d8-bc3e-eb88-2c692fa806f8", // generated by the old runtime
	} {
		if err := query.ValidateProject(value); err == nil {
			t.Fatalf("non-v4 UUID accepted: %s", value)
		}
	}
}

func TestRunBackendQueriesStartsTogetherAndPreservesOrder(t *testing.T) {
	started := make(chan string, 2)
	release := make(chan struct{})
	resultsDone := make(chan []backendResult, 1)
	go func() {
		resultsDone <- runBackendQueries(context.Background(), []backendQuery{
			{name: "logs", fn: func(context.Context) (any, error) {
				started <- "logs"
				<-release
				return "logs-result", nil
			}},
			{name: "metrics", fn: func(context.Context) (any, error) {
				started <- "metrics"
				<-release
				return "metrics-result", nil
			}},
		})
	}()

	seen := map[string]bool{}
	for i := 0; i < 2; i++ {
		select {
		case name := <-started:
			seen[name] = true
		case <-time.After(time.Second):
			close(release)
			t.Fatal("independent backend calls did not start concurrently")
		}
	}
	if !seen["logs"] || !seen["metrics"] {
		close(release)
		t.Fatalf("started backends = %#v", seen)
	}
	close(release)
	select {
	case results := <-resultsDone:
		if len(results) != 2 || results[0].name != "logs" || results[1].name != "metrics" {
			t.Fatalf("result order = %#v", results)
		}
	case <-time.After(time.Second):
		t.Fatal("parallel backend query did not finish")
	}
}

func TestRetryOnlyRetriesTransientFailures(t *testing.T) {
	tests := []struct {
		name string
		err  error
		want int
	}{
		{name: "no data", err: query.ErrNoData, want: 1},
		{name: "bad request", err: query.BackendHTTPError{StatusCode: http.StatusBadRequest}, want: 1},
		{name: "service unavailable", err: query.BackendHTTPError{StatusCode: http.StatusServiceUnavailable}, want: 2},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			calls := 0
			_, err := retry(context.Background(), func() (any, error) {
				calls++
				return nil, tc.err
			})
			if err != tc.err || calls != tc.want {
				t.Fatalf("err=%v calls=%d, want err=%v calls=%d", err, calls, tc.err, tc.want)
			}
		})
	}
}

func TestQueryVersionAdvertisesQueryCapabilities(t *testing.T) {
	r := httptest.NewRequest(http.MethodGet, "http://gateway/v1/version", nil)
	rr := httptest.NewRecorder()
	queryVersion(rr, r)
	if rr.Code != http.StatusOK {
		t.Fatalf("version status = %d", rr.Code)
	}
	var body map[string]any
	if err := json.Unmarshal(rr.Body.Bytes(), &body); err != nil {
		t.Fatal(err)
	}
	capabilities, ok := body["capabilities"].([]any)
	if !ok {
		t.Fatalf("capabilities = %#v", body["capabilities"])
	}
	for _, want := range []string{"context", "errors", "correlate", "services"} {
		found := false
		for _, value := range capabilities {
			if value == want {
				found = true
			}
		}
		if !found {
			t.Fatalf("capabilities missing %q: %#v", want, capabilities)
		}
	}
	if _, ok := body["ingest"]; ok {
		t.Fatal("query version exposed ingest capability")
	}
	if body["gateway_version"] != buildVersion {
		t.Fatalf("gateway version = %#v, want build version %q", body["gateway_version"], buildVersion)
	}
}

func TestGatewayVersionUsesRuntimeOverride(t *testing.T) {
	t.Setenv("GATEWAY_VERSION", "2.0.1")
	if got := gatewayVersion(); got != "2.0.1" {
		t.Fatalf("gateway version = %q, want runtime version", got)
	}
}

func BenchmarkProject100Records(b *testing.B) {
	items := make([]any, 100)
	for i := range items {
		items[i] = map[string]any{
			"trace_id":      "0123456789abcdef0123456789abcdef",
			"service_name":  "api",
			"message":       "telemetry",
			"status_code":   float64(200),
			"authorization": "must be dropped",
		}
	}
	input := map[string]any{"items": items}
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		project(input)
	}
}

func request(path, method, token, body string) *http.Request {
	r := httptest.NewRequest(method, "http://gateway"+path, strings.NewReader(body))
	r.Header.Set("Authorization", "Bearer "+token)
	r.Header.Set("Content-Type", "application/x-protobuf")
	return r
}

func TestAuthIsUniformAndEndpointsArePOSTOnly(t *testing.T) {
	c := config{token: "secret", maxConcurrent: 1}
	sem := make(chan struct{}, 1)
	for _, path := range ingestPaths {
		for _, token := range []string{"", "wrong", "secretx"} {
			rr := httptest.NewRecorder()
			handleIngest(c, sem, path, rr, request(path, http.MethodPost, token, "x"))
			if rr.Code != http.StatusUnauthorized || rr.Body.String() != "Unauthorized\n" {
				t.Fatalf("%s token %q: got %d %q", path, token, rr.Code, rr.Body.String())
			}
		}
		rr := httptest.NewRecorder()
		handleIngest(c, sem, path, rr, request(path, http.MethodGet, "secret", ""))
		if rr.Code != http.StatusMethodNotAllowed {
			t.Fatalf("%s GET: got %d", path, rr.Code)
		}
	}
}

func TestQueryHealthRequiresQueryToken(t *testing.T) {
	c := config{queryToken: "query-secret"}
	for _, token := range []string{"", "wrong"} {
		rr := httptest.NewRecorder()
		queryHealth(c)(rr, request("/v1/health", http.MethodGet, token, ""))
		if rr.Code != http.StatusUnauthorized {
			t.Fatalf("token %q: got %d", token, rr.Code)
		}
	}
	rr := httptest.NewRecorder()
	queryHealth(c)(rr, request("/v1/health", http.MethodGet, "query-secret", ""))
	if rr.Code != http.StatusOK || !strings.Contains(rr.Body.String(), `"status":"ok"`) {
		t.Fatalf("valid token: got %d %q", rr.Code, rr.Body.String())
	}
}

func TestIngestForwardsOnlyProtobufAndMapsUpstream(t *testing.T) {
	var got *http.Request
	var gotBody string
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r
		body, _ := io.ReadAll(r.Body)
		gotBody = string(body)
		if r.URL.Path != "/v1/logs" {
			t.Errorf("upstream path = %s", r.URL.Path)
		}
		w.WriteHeader(http.StatusAccepted)
	}))
	defer upstream.Close()
	c := config{token: "secret", upstream: upstream.URL, maxConcurrent: 1}
	sem := make(chan struct{}, 1)
	r := request("/v1/logs", http.MethodPost, "secret", "protobuf")
	for _, key := range []string{"Cookie", "Set-Cookie", "Proxy-Authorization", "X-Forwarded-For"} {
		r.Header.Set(key, "must-not-forward")
	}
	rr := httptest.NewRecorder()
	if status := handleIngest(c, sem, "/v1/logs", rr, r); status != http.StatusAccepted {
		t.Fatalf("status = %d", status)
	}
	if got == nil || got.Header.Get("Content-Type") != "application/x-protobuf" || got.Header.Get("Authorization") != "" || got.Header.Get("Cookie") != "" {
		t.Fatalf("sensitive headers forwarded: %#v", got)
	}
	if gotBody != "protobuf" {
		t.Fatalf("body = %q", gotBody)
	}
}

func TestIngestRejectsRedirectWithoutDisclosingBody(t *testing.T) {
	targetHits := 0
	target := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		targetHits++
		_, _ = io.Copy(io.Discard, r.Body)
	}))
	defer target.Close()
	redirect := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, target.URL, http.StatusTemporaryRedirect)
	}))
	defer redirect.Close()
	c := config{token: "secret", upstream: redirect.URL, maxConcurrent: 1}
	sem := make(chan struct{}, 1)
	r := request("/v1/logs", http.MethodPost, "secret", "sensitive-telemetry")
	r.Header.Set("Content-Type", "application/x-protobuf")
	rr := httptest.NewRecorder()
	if got := handleIngest(c, sem, "/v1/logs", rr, r); got != http.StatusTemporaryRedirect {
		t.Fatalf("redirect status = %d", got)
	}
	if targetHits != 0 {
		t.Fatalf("redirect target received telemetry: %d hits", targetHits)
	}
}

func TestQueryConcurrencyIsBoundedAndExplicit(t *testing.T) {
	entered := make(chan struct{})
	release := make(chan struct{})
	backend := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		select {
		case entered <- struct{}{}:
		default:
		}
		<-release
		_, _ = w.Write([]byte(`{"data":[]}`))
	}))
	defer backend.Close()
	c := config{
		queryToken:         "query-secret",
		queryMaxConcurrent: 1,
		querySem:           make(chan struct{}, 1),
		query:              query.Client{Traces: backend.URL},
	}
	h := queryHandler(c, "/v1/services")
	firstDone := make(chan *httptest.ResponseRecorder, 1)
	go func() {
		rr := httptest.NewRecorder()
		h(rr, request("/v1/services", http.MethodGet, "query-secret", ""))
		firstDone <- rr
	}()
	select {
	case <-entered:
	case <-time.After(time.Second):
		t.Fatal("first query did not reach backend")
	}
	second := httptest.NewRecorder()
	h(second, request("/v1/services", http.MethodGet, "query-secret", ""))
	if second.Code != http.StatusTooManyRequests || second.Body.String() != "query overloaded\n" || second.Header().Get("Retry-After") != "1" {
		t.Fatalf("overload response = %d %q retry-after=%q", second.Code, second.Body.String(), second.Header().Get("Retry-After"))
	}
	close(release)
	select {
	case rr := <-firstDone:
		if rr.Code != http.StatusOK {
			t.Fatalf("first query status = %d", rr.Code)
		}
	case <-time.After(time.Second):
		t.Fatal("first query did not finish")
	}
}

func TestCorrelateForwardsProjectToLogsAndMetrics(t *testing.T) {
	var logQuery, metricsQuery string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/select/jaeger/api/traces/0123456789abcdef0123456789abcdef":
			_, _ = w.Write([]byte(`{"data":[{"spans":[{"spanID":"span","operationName":"GET","startTime":1000000,"duration":1000,"processID":"p1"}],"processes":{"p1":{"serviceName":"api","tags":[{"key":"project","value":"123e4567-e89b-42d3-a456-426614174000"}]}}}]}`))
		case r.URL.Path == "/select/logsql/query":
			logQuery = r.URL.Query().Get("query")
			_, _ = w.Write([]byte(`[{"trace_id":"0123456789abcdef0123456789abcdef"}]`))
		case r.URL.Path == "/api/v1/query":
			metricsQuery = r.URL.Query().Get("query")
			_, _ = w.Write([]byte(`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"service_name":"api"},"value":[1700000060,"1"]}]}}`))
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()
	project := "123e4567-e89b-42d3-a456-426614174000"
	c := config{
		queryToken: "query-secret",
		querySem:   make(chan struct{}, 1),
		query:      query.Client{Logs: server.URL, Metrics: server.URL, Traces: server.URL},
	}
	r := httptest.NewRequest(http.MethodPost, "http://gateway/v1/correlate", strings.NewReader(`{"trace_id":"0123456789abcdef0123456789abcdef","project":"`+project+`"}`))
	r.Header.Set("Authorization", "Bearer query-secret")
	r.Header.Set("Content-Type", "application/json")
	rr := httptest.NewRecorder()
	queryHandler(c, "/v1/correlate")(rr, r)
	if rr.Code != http.StatusOK {
		t.Fatalf("correlate status = %d body=%s", rr.Code, rr.Body.String())
	}
	if !strings.Contains(logQuery, `project:"`+project+`"`) {
		t.Fatalf("correlate log query = %q", logQuery)
	}
	if !strings.Contains(metricsQuery, `project="`+project+`"`) {
		t.Fatalf("correlate metrics query = %q", metricsQuery)
	}
	wrongProject := "223e4567-e89b-42d3-a456-426614174000"
	wrong := httptest.NewRequest(http.MethodPost, "http://gateway/v1/correlate", strings.NewReader(`{"trace_id":"0123456789abcdef0123456789abcdef","project":"`+wrongProject+`"}`))
	wrong.Header.Set("Authorization", "Bearer query-secret")
	wrong.Header.Set("Content-Type", "application/json")
	wrongRR := httptest.NewRecorder()
	queryHandler(c, "/v1/correlate")(wrongRR, wrong)
	if wrongRR.Code != http.StatusOK || !strings.Contains(wrongRR.Body.String(), `"status":"no_matching_data"`) || strings.Contains(wrongRR.Body.String(), `"correlation"`) {
		t.Fatalf("wrong project correlate = %d %s", wrongRR.Code, wrongRR.Body.String())
	}
}

func TestServicesWithProjectNeverUsesGlobalTraceServiceList(t *testing.T) {
	traceHits := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/select/jaeger/api/services":
			traceHits++
			_, _ = w.Write([]byte(`{"data":["other-project"]}`))
		case "/select/logsql/query":
			if !strings.Contains(r.URL.Query().Get("query"), `project:"550e8400-e29b-41d4-a716-446655440000"`) {
				t.Errorf("unscoped log query: %q", r.URL.RawQuery)
			}
			_, _ = w.Write([]byte(`[{"service_name":"worker"}]`))
		case "/api/v1/query":
			if !strings.Contains(r.URL.Query().Get("query"), `project="550e8400-e29b-41d4-a716-446655440000"`) {
				t.Errorf("unscoped metric query: %q", r.URL.RawQuery)
			}
			_, _ = w.Write([]byte(`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"service_name":"api"},"value":[1700000060,"1"]}]}}`))
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()
	c := config{queryToken: "query-secret", querySem: make(chan struct{}, 1), query: query.Client{Logs: server.URL, Metrics: server.URL, Traces: server.URL}}
	r := httptest.NewRequest(http.MethodGet, "http://gateway/v1/services?project=550e8400-e29b-41d4-a716-446655440000", nil)
	r.Header.Set("Authorization", "Bearer query-secret")
	rr := httptest.NewRecorder()
	queryHandler(c, "/v1/services")(rr, r)
	if rr.Code != http.StatusOK || traceHits != 0 {
		t.Fatalf("status=%d trace_hits=%d body=%s", rr.Code, traceHits, rr.Body.String())
	}
	if !strings.Contains(rr.Body.String(), `"services":["api","worker"]`) || strings.Contains(rr.Body.String(), "other-project") {
		t.Fatalf("project-scoped services response = %s", rr.Body.String())
	}
}

func TestBodyAndContentContract(t *testing.T) {
	c := config{token: "secret", upstream: "http://127.0.0.1:1", maxConcurrent: 1}
	sem := make(chan struct{}, 1)
	for _, contentType := range []string{"", "application/json", "application/x-protobuf; charset=binary"} {
		r := request("/v1/traces", http.MethodPost, "secret", "x")
		r.Header.Set("Content-Type", contentType)
		rr := httptest.NewRecorder()
		status := handleIngest(c, sem, "/v1/traces", rr, r)
		if contentType == "application/x-protobuf; charset=binary" {
			if status != http.StatusBadGateway { // valid content type reaches the unavailable upstream
				t.Fatalf("valid content type status = %d", status)
			}
		} else if status != http.StatusBadRequest {
			t.Fatalf("content type %q status = %d", contentType, status)
		}
	}
	r := request("/v1/metrics", http.MethodPost, "secret", strings.Repeat("x", maxBody+1))
	rr := httptest.NewRecorder()
	if status := handleIngest(c, sem, "/v1/metrics", rr, r); status != http.StatusRequestEntityTooLarge {
		t.Fatalf("oversize status = %d", status)
	}
}

func TestLoadRejectsUnsafeUpstream(t *testing.T) {
	t.Setenv("GATEWAY_INGEST_TOKEN", "secret")
	t.Setenv("GATEWAY_QUERY_TOKEN", "different-secret")
	for _, upstream := range []string{"https://collector:4318", "http://collector:4318/path", "http://collector:4318?x=1", "collector:4318"} {
		t.Setenv("GATEWAY_COLLECTOR_URL", upstream)
		if _, err := load(); err == nil {
			t.Fatalf("upstream %q accepted", upstream)
		}
	}
}

func TestLoadRejectsMissingOrEqualTokens(t *testing.T) {
	t.Setenv("GATEWAY_COLLECTOR_URL", "http://collector:4318")
	t.Setenv("GATEWAY_INGEST_TOKEN", "")
	t.Setenv("GATEWAY_QUERY_TOKEN", "query-secret")
	if _, err := load(); err == nil {
		t.Fatal("missing ingest token accepted")
	}
	t.Setenv("GATEWAY_INGEST_TOKEN", "same-secret")
	t.Setenv("GATEWAY_QUERY_TOKEN", "same-secret")
	if _, err := load(); err == nil {
		t.Fatal("equal ingest/query tokens accepted")
	}
}

func TestLoadBoundsQueryConcurrency(t *testing.T) {
	t.Setenv("GATEWAY_INGEST_TOKEN", "secret")
	t.Setenv("GATEWAY_QUERY_TOKEN", "different-secret")
	t.Setenv("GATEWAY_COLLECTOR_URL", "http://collector:4318")
	t.Setenv("GATEWAY_QUERY_MAX_CONCURRENT", "7")
	c, err := load()
	if err != nil || c.queryMaxConcurrent != 7 {
		t.Fatalf("configured query concurrency = %d, err=%v", c.queryMaxConcurrent, err)
	}
	for _, value := range []string{"0", "129", "not-a-number"} {
		t.Setenv("GATEWAY_QUERY_MAX_CONCURRENT", value)
		if _, err := load(); err == nil {
			t.Fatalf("query concurrency %q accepted", value)
		}
	}
}

func TestTokenFileSupportsRawAndXDGJSON(t *testing.T) {
	raw := t.TempDir() + "/raw"
	if err := os.WriteFile(raw, []byte(" raw-secret\n"), 0600); err != nil {
		t.Fatal(err)
	}
	got, err := tokenFile(raw, "ingest_token")
	if err != nil || got != "raw-secret" {
		t.Fatalf("raw token = %q, err = %v", got, err)
	}
	jsonFile := t.TempDir() + "/credentials"
	if err := os.WriteFile(jsonFile, []byte(`{"ingest_token":"ingest-secret","query_token":"query-secret"}`), 0600); err != nil {
		t.Fatal(err)
	}
	got, err = tokenFile(jsonFile, "query_token")
	if err != nil || got != "query-secret" {
		t.Fatalf("JSON token = %q, err = %v", got, err)
	}
}
