apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 10s

  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    editable: true
    jsonData:
      vmuiUrl: http://localhost:9428/select/vmui/
      logLevelRules:
        - field: severity_text
          value: error
          level: error
          operator: equals
          enabled: true
        - field: severity_text
          value: warn
          level: warning
          operator: equals
          enabled: true
        - field: severity_text
          value: info
          level: info
          operator: equals
          enabled: true

  - name: VictoriaTraces
    uid: victoriatraces
    type: jaeger
    access: proxy
    url: http://victoriatraces:10428/select/jaeger
    editable: true
